openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: |
    API para el manejo de tareas con autenticación mediante una API de seguridad externa.  
    **Autenticación**: Requiere un JWT en la cookie `token`, validado por la API de seguridad en `${AUTH_API_URL}/users/profile`.  
    **CSRF Protection**: Los endpoints POST, PUT y DELETE requieren el header `X-XSRF-TOKEN` que coincida con la cookie `XSRF-TOKEN`.  
    Para obtener la cookie `XSRF-TOKEN`, realiza una solicitud GET a cualquier endpoint (e.g., `GET /tasks`).  
    **Instrucciones para Postman**:  
    1. Habilita el cookie jar en Postman.  
    2. Realiza una solicitud `GET /tasks` para obtener la cookie `XSRF-TOKEN`.  
    3. Copia el valor de `XSRF-TOKEN` desde la pestaña Cookies.  
    4. Incluye `X-XSRF-TOKEN: [valor]` en los headers de las solicitudes POST, PUT, DELETE.
servers:
  - url: http://localhost:3000
    description: Servidor local
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
      description: JWT access token stored in an HTTP-only cookie, validated by the external security API.
    csrfToken:
      type: apiKey
      in: header
      name: X-XSRF-TOKEN
      description: |
        CSRF token required for POST, PUT, DELETE requests. Must match the `XSRF-TOKEN` cookie.  
        Obtain it via a GET request (e.g., `GET /tasks`).
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: ID único de la tarea
          example: 60d0fe4f5311236168a109ca
        title:
          type: string
          description: Título de la tarea (máx. 50 caracteres)
          example: Completar proyecto
        description:
          type: string
          description: Descripción corta de la tarea (máx. 200 caracteres)
          example: Terminar la API de tareas
        longDescription:
          type: string
          description: Descripción extendida de la tarea (máx. 2000 caracteres)
          example: Este proyecto requiere completar una API RESTful con Express y MongoDB.
        createdAt:
          type: string
          format: date-time
          description: Fecha de creación de la tarea
          example: 2025-08-05T14:55:00.000Z
        startDate:
          type: string
          format: date-time
          description: Fecha de inicio de la tarea
          example: 2025-08-06T09:00:00.000Z
        dueDate:
          type: string
          format: date-time
          description: Fecha de finalización de la tarea
          example: 2025-08-10T23:59:59.000Z
        status:
          type: string
          enum: [Sin iniciar, En curso, Completado]
          description: Estado de la tarea
          example: Sin iniciar
        userId:
          type: string
          description: ID del usuario propietario de la tarea
          example: 507f1f77bcf86cd799439011
      required:
        - title
        - description
        - startDate
        - dueDate
        - userId
    TaskInput:
      type: object
      properties:
        title:
          type: string
          description: Título de la tarea (máx. 50 caracteres)
          example: Completar proyecto
        description:
          type: string
          description: Descripción corta de la tarea (máx. 200 caracteres)
          example: Terminar la API de tareas
        longDescription:
          type: string
          description: Descripción extendida de la tarea (máx. 2000 caracteres)
          example: Este proyecto requiere completar una API RESTful con Express y MongoDB.
        startDate:
          type: string
          format: date-time
          description: Fecha de inicio de la tarea
          example: 2025-08-06T09:00:00.000Z
        dueDate:
          type: string
          format: date-time
          description: Fecha de finalización de la tarea
          example: 2025-08-10T23:59:59.000Z
        status:
          type: string
          enum: [Sin iniciar, En curso, Completado]
          description: Estado de la tarea
          example: Sin iniciar
      required:
        - title
        - description
        - startDate
        - dueDate
    Error:
      type: object
      properties:
        status:
          type: string
          enum: [error]
          example: error
        message:
          type: string
          example: Error al obtener las tareas
        errors:
          type: array
          items:
            type: object
            properties:
              msg:
                type: string
              param:
                type: string
              location:
                type: string
              value:
                type: string
paths:
  /tasks:
    get:
      summary: Obtener todas las tareas del usuario autenticado
      tags:
        - Tasks
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de todas las tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Crear una nueva tarea
      tags:
        - Tasks
      security:
        - cookieAuth: []
        - csrfToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskInput"
      responses:
        "201":
          description: Tarea creada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Error en los datos enviados
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Invalid or missing CSRF token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                example:
                  status: error
                  message: invalid csrf token
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tasks/{id}:
    get:
      summary: Obtener una tarea por ID
      tags:
        - Tasks
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la tarea
      responses:
        "200":
          description: Tarea encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Actualizar una tarea existente
      tags:
        - Tasks
      security:
        - cookieAuth: []
        - csrfToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la tarea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskInput"
      responses:
        "200":
          description: Tarea actualizada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Error en los datos enviados
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Invalid or missing CSRF token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                example:
                  status: error
                  message: invalid csrf token
        "404":
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Eliminar una tarea
      tags:
        - Tasks
      security:
        - cookieAuth: []
        - csrfToken: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la tarea
      responses:
        "200":
          description: Tarea eliminada
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Tarea eliminada correctamente
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Invalid or missing CSRF token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                example:
                  status: error
                  message: invalid csrf token
        "404":
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "429":
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tasks/by-title/{title}:
    get:
      summary: Obtener una tarea por título
      tags:
        - Tasks
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: title
          schema:
            type: string
          required: true
          description: Título de la tarea (búsqueda exacta, insensible a mayúsculas/minúsculas)
      responses:
        "200":
          description: Tarea encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Tarea no encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
